In [1]:
import numpy as np
import cv2

In [12]:
img= cv2.imread('images/opencv.jpg')
img = cv2.resize(img,(512,512))
imgray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
_,thresh = cv2.threshold(imgray,20,255,0)
contours,hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
print("Number of contous = "+str(len(contours)))
print(contours[0])
cv2.drawContours(img,contours,-1,(0,255,0),3)
cv2.imshow('Image',img)
cv2.imshow('Image GRAY',imgray)
cv2.imshow('thresh',thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contous = 12
[[[265 343]]

 [[264 344]]

 [[263 344]]

 [[263 345]]

 [[262 346]]

 [[261 345]]

 [[261 344]]

 [[260 344]]

 [[259 344]]

 [[258 344]]

 [[257 344]]

 [[256 344]]

 [[256 345]]

 [[256 346]]

 [[256 347]]

 [[256 348]]

 [[256 349]]

 [[256 350]]

 [[256 351]]

 [[256 352]]

 [[256 353]]

 [[256 354]]

 [[256 355]]

 [[256 356]]

 [[256 357]]

 [[256 358]]

 [[256 359]]

 [[256 360]]

 [[256 361]]

 [[256 362]]

 [[256 363]]

 [[256 364]]

 [[256 365]]

 [[256 366]]

 [[256 367]]

 [[256 368]]

 [[256 369]]

 [[256 370]]

 [[256 371]]

 [[256 372]]

 [[257 373]]

 [[258 373]]

 [[259 373]]

 [[260 373]]

 [[261 373]]

 [[261 372]]

 [[261 371]]

 [[261 370]]

 [[261 369]]

 [[261 368]]

 [[261 367]]

 [[261 366]]

 [[261 365]]

 [[261 364]]

 [[261 363]]

 [[261 362]]

 [[261 361]]

 [[261 360]]

 [[261 359]]

 [[261 358]]

 [[261 357]]

 [[261 356]]

 [[261 355]]

 [[261 354]]

 [[261 353]]

 [[262 352]]

 [[263 351]]

 [[264 350]]

 [[265 350]]

 [[266 349]